GET http://localhost:3001/api/notes


###

DELETE http://localhost:3001/api/notes/2

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "JSON is easy but cumbersome to learn"
    "important" : true
}